/**
 * Conformance golden generator (run manually: `npm run gen:conformance`).
 *
 * Reads the local Chromium checkout's inspector-protocol accessibility goldens
 * and vendors each `<name>-expected.txt` into tests/ax/conformance.expected.ts
 * as an embedded string. The conformance suite then asserts our ax-tree.ts
 * output against these vendored expectations with NO Chromium dependency at run
 * time — so the tests run anywhere, including GitHub Actions.
 *
 * Regenerate when ax-tree.ts changes the wire format, when a fixture/driver in
 * _conformance.ts changes, or when syncing to a newer Chromium. The case list
 * (names + which are ceiling-only) is the single source of truth in
 * _conformance.ts; ceiling cases have no byte-asserted golden and are skipped.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { CASES } from "../tests/ax/_conformance.ts";

const GOLDEN_DIR = path.join(
  os.homedir(),
  ".btca/agent/sandbox/chromium-src/third_party/blink/web_tests/http/tests/inspector-protocol/accessibility",
);
const OUT = path.join(import.meta.dirname, "..", "tests", "ax", "conformance.expected.ts");

/** Escape a golden so it survives embedding inside a `template literal`. */
function escapeTemplate(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main(): void {
  if (!fs.existsSync(GOLDEN_DIR)) {
    console.error(`Chromium golden directory not found:\n  ${GOLDEN_DIR}`);
    console.error(
      "This generator needs the local Chromium checkout (see the memory note 'chromium-source-checkout').",
    );
    process.exit(1);
  }

  const asserted = CASES.filter((c) => !c.ceiling);
  const missing: string[] = [];
  const entries = asserted.map((c) => {
    const golden = path.join(GOLDEN_DIR, `${c.name}-expected.txt`);
    if (!fs.existsSync(golden)) {
      missing.push(c.name);
      return "";
    }
    const text = fs.readFileSync(golden, "utf8");
    return `  ${JSON.stringify(c.name)}: \`${escapeTemplate(text)}\`,`;
  });

  if (missing.length) {
    console.error(`Missing golden files for:\n  ${missing.join("\n  ")}`);
    process.exit(1);
  }

  const header = `// GENERATED by \`npm run gen:conformance\` — do not edit by hand.
//
// Vendored expected output of Chromium's inspector-protocol accessibility
// goldens (web_tests/http/tests/inspector-protocol/accessibility/<name>-expected.txt),
// embedded so the conformance suite runs with no Chromium dependency (CI-safe).
// Regenerate after wire-format changes or a Chromium sync: npm run gen:conformance
`;
  fs.writeFileSync(
    OUT,
    `${header}\nexport const EXPECTED: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
  );

  // Normalize formatting so `npm run check` stays clean.
  execFileSync("oxfmt", [path.relative(process.cwd(), OUT)], { stdio: "inherit" });
  console.log(`Vendored ${asserted.length} goldens → ${path.relative(process.cwd(), OUT)}`);
}

main();
